import Head from "next/head";
import Image from "next/image";
import Temperature from "../component/Temperature";
import styles from "../styles/Home.module.css";
import Stack from "@mui/material/Stack";
import Currency from "../component/Currency";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="row">
        <Stack direction="row">
          <main className={styles.main}>
            <h1 className={styles.title}> Temperature Converter </h1>
            <p className={styles.description}> Convert Fahrenheit and Celsius To Each Other </p>
            <div className="container">
              <Temperature />
            </div>
          </main>
          <main className={styles.main}>
            <h1 className={styles.title}> Currency Converter </h1>
            <p className={styles.description}> Convert Any Currency To Each Other </p>
            <div className="container">
              <Currency />
            </div>
          </main>
        </Stack>
      </div>
    </div>
  );
}
